<?php
/**
 * @file
 * Code for the CRF Non-Cluster Requests feature.
 */

include_once 'crf_non_cluster_requests.features.inc';


/**
 * Implements hook_form_FORM_ID_alter().
 */
function crf_non_cluster_requests_form_non_cluster_request_node_form_alter(&$form, &$form_state, $form_id) {
  $node = $form['#node'];
  if (!isset($node->nid)) {  
    $form['actions']['submit']['#value'] = t('Create & Send Info Request');
    
    // Help link
    $help_link = theme('advanced_help_topic', array(
      'module' => 'crf_non_cluster_requests',
      'topic' => 'request-email',
    ));
    $form['field_append_to_alert_email']['#prefix'] = $help_link . '&nbsp;' . t('Show me an Information Request email example');
  }
}